# Enable C++ support
sudo: required
dist: trusty
language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - cmake
      - cmake-data
      - gcc-5
      - g++-5
      - clang-3.8
# Compiler selection
compiler:
  - gcc
  - clang
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make check && make package

